apiVersion: apps/v1
kind: Deployment
metadata:
  name: limiter-deployment
  labels:
    app: limiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limiter
  template:
    metadata:
      labels:
        app: limiter
    spec:
      containers:
      - name: limiter
        image: docker.io/library/limiter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: limiter-service
spec:
  selector:
    app: limiter
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
