apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-server
        image: docker.io/library/python_server_limited:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_URl
          value: "http://node-service.default.svc.cluster.local:5000"
        - name: LIMITER_URL
          value: "http://limiter-service.default.svc.cluster.local:5002"


---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
